---
language: go
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - make build
  - test -f bin/amd64/rdss-siegfried-service
  - make container
  - docker images | grep artefactual/rdss-siegfried-service-amd64
  - make test
notifications:
  email: false
